### PR TITLE
Fix Travis CI build

### PR DESCRIPTION
**Pull request by MatElGran**
As some PR are waiting for CI to be back to green, and I would love for this gem to be compatible with newer versions of graphql-ruby gem, I thought I could try and fix current problems. 

Please let me know if you're not happy with the decisions I made regarding rubocop alerts

### CODE REVIEW

**Comment by opiation** [comment]
Anything blocking this PR, @khamusa?  A few other PRs are pending this CI fix including support for the latest GraphQL 1.8 class-based API.  Is there anything else the community can help with to move this forward?

**Comment by ericraio** [comment]
Is the author still active?

**Comment by opiation** [comment]
@ericraio, the author does not seem to be active.

For what it's worth, I've migrated to the class-based API and replaced all the matchers with queries that request the field previously covered by said matchers.  While there may be some slight disadvantages to this change, in general this has resulted in an increase in test coverage.  The GraphQL engine checks types **very** strictly so merely querying for the field(s) enforces type-checking as defined in your types.  So, I sort of use the ruby GraphQL type classes and inputs themselves as matcher tests with the caveat that every field from every type must be queried at least once during tests.

**Comment by ericraio** [comment]
> @ericraio, the author does not seem to be active.
> 
> For what it's worth, I've migrated to the class-based API and replaced all the matchers with queries that request the field previously covered by said matchers. While there may be some slight disadvantages to this change, in general this has resulted in an increase in test coverage. The GraphQL engine checks types **very** strictly so merely querying for the field(s) enforces type-checking as defined in your types. So, I sort of use the ruby GraphQL type classes and inputs themselves as matcher tests with the caveat that every field from every type must be queried at least once during tests.

Awesome! Could you share a quick example? I'd greatly appreciate it

**Comment by opiation** [comment]
Assuming the schema class is `MySchema` and type is `UserType`...

```ruby
# app/graphql/types/user_type.rb

module Types
  class UserType < BaseObject
    field :id, ID, null: false
    field :first_name, String, null: true
    field :last_name, String, null: true
    field :email, String, null: false
  end
end
```

```ruby
# spec/graphql/my_schema_user_spec.rb
# Presumes there's a `user` query

RSpec.describe MySchema do
  let(:query) do
    <<~GRAPHQL
      query($id: ID) {
        # User query should at least shallowly request each field in UserType
        user(id: $id) {
          id
          firstName
          lastName
          email
        }
      }
    GRAPHQL
  end

  let(:context) { {} } # Your query test context here, like `current_user` etc...

  # [Setup existing users here]

  context "when no user ID is provided" do
    let(:variables) { {} }

    it "returns the current user" do
      result = described_class.execute(query, context: context, variables: variables)
      # [define expectation here]
    end
  end

  context "when user ID is provided" do
    let(:variables) { { id: 42 } }

    it "returns the requested user with given ID" do
      result = described_class.execute(query, context: context, variables: variables)
      # [define expectation here]
    end
  end
end
```

In the contrived example above, the key element I described is that the _user_ query fetches at least shallowly each field defined in `UserType`.  This ensures (even if unchecked in `it` expectations) that said fields in fact conform to the types as defined in `UserType`, which is kind of what `have_a_field(x).that_returns(y)` does.  This approach does not validate any business logic but neither do those kinds of matchers.

The main downside is such tests take longer as they actually query the DB, versus checking type definitions.  Nonetheless, if you favor more _feature_-like tests, this is in that vein of test type.

**Comment by khamusa** [comment]
I've released a new version of the gem that is compatible with the class based api while also keeping support for the legacy api. I didn't use this branch since I already intended to do a broader refactor in the code.

Thanks anyway for the contribution, and sorry for being inactive for so long, I'm back now.

**Pull request closed without merging**
